# Meta information: PyPI and Pip

[project]
name = 'andi-py'
authors = [{name='Florian Kolbl - Yannick Bornat - Louis Regnacq'}]
license = {file='License.txt'}
keywords = ['osciloscope', 'hardware', 'electronics', 'measurements']
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Operating System :: MacOS :: MacOS X',
    'Topic :: Engineering :: Electronics',
    'Intended Audience :: Science/Research',
    'Natural Language :: English']
readme = 'pypi.md'
requires-python = '>=3.6'
dependencies = ['numpy']
dynamic = ['version', 'description']

[project.urls]
Documentation = 'https://andi.readthedocs.io'
Source = 'https://github.com/fkolbl/andi'